name: Terraform CI/CD Workflow

on:
  push:
    branches:
      - develop
      - production
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "eu-west-1"

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: |
        terraform init -reconfigure \
          -backend-config="bucket=boocampusers" \
          -backend-config="key=${{ github.ref_name }}/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="dynamodb_table=terraform-locks" \
          -backend-config="encrypt=true"

    - name: Terraform Workspace
      run: |
        terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }}

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=plan.tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'workflow_dispatch'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: |
        terraform init -reconfigure \
          -backend-config="bucket=boocampusers" \
          -backend-config="key=${{ github.ref_name }}/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}" \
          -backend-config="dynamodb_table=terraform-locks" \
          -backend-config="encrypt=true"

    - name: Terraform Workspace
      run: |
        terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }}

    - name: Terraform Apply (Manual)
      run: terraform apply plan.tfplan
